
#Read the documentation in hub.docker.com from mysql package
# sudo docker run -d -e "MYSQL_ROOT_PASSWORD=my-secret-pw" mysql:<tag>

# sudo docker run -d --name my-db2 -p 3333:3306 -e "MYSQL_ROOT_PASSWORD=1234" -e "MYSQL_DATABASE=docker-db" -e "MYSQL_USER=docker-user" -e "MYSQL_PASSWORD=4321" mysql:5.7 


LABEL if you want to create a docker with mongo:

# sudo docker -d --name my-mongoxd -p 27017:27017 mongo:4.2

LABEL if you want to create a postgres docker container:

# sudo docker run -d --name my-postgres -e "POSTGRES_PASSWORD=1234" -e "POSTGRES_USER=docker" -e "POSTGRES_DB=docker-db" -p 5432:5432 postgres

