version: '3'
services:
#  apache-web:
#    container_name: apache-web
#    image: apache666:test
#    build: .
#    cpuset: "0"
#    mem_limit: "50m"
#    environment:
#      ENV: env
#      VIRTUALIZATION: docker
#    ports:
#      - "5555:80"
#    networks:
#      - my-net
#    volumes:
#      - ./html:/var/www/html
  db:
    container_name: db-mysql
    image: mysql:5.7
    env_file: common.env
#    volumes:
#      - "db_data:/var/lib/mysql/data"
    ports:
      - 3306:3306
    networks:
      - my-net
  phpmyadmin:
    container_name: php-my-admin
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      DATABASE_HOST: db
    depends_on:
      - db
    networks:
      - my-net
networks:
  my-net:
#volumes:
#  db_data:
