FROM centos:7

ENV prueba ohHiMark

RUN useradd dieguito

#USER dieguito

#Examplo of restrict RAM and CPU in a building docker:

# sudo docker run -d -m "250mb" --cpuset-cpus (0-1) --name my-mongo mongo:4.2
