
# Ejemplo: No funcionó phpinfo por falta de tiempo
# sudo docker run -d --name test -p 5555:80 -e "ENV=env" -e "VIRTUALIZATION=docker" -m "50mb" --cpuset-cpus 0 -v $PWD/source1:/var/www/html apache:phpinfo
