version: '3'
services:
  db-mysql:
    container_name: ps-mysql
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ps
      MYSQL_USER: ps
      MYSQL_PASSWORD: ps
    ports:
      - "3306:3306"
    networks:
      - my_net

  ps:
    container_name: ps-web
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db-mysql
    image: prestashop/prestashop
    ports:
      - "80:80"
    environment:
      DB_SERVER: db-mysql
      DB_USER: ps
      DB_PASSWD: ps
      DB_NAME: ps
    networks:
      - my_net

networks:
  my_net:
