FROM centos:7

VOLUME /opt/

# Para que lo pruebes:

# sudo docker volume create my-vol
# sudo docker run -d --name my-db2 -p 3308:3306 -e "MYSQL_ROOT_PASSWORD=1234" -v my-vol:/var/lib/mysql mysql:5.7



# otro:

# sudo docker run -p 8080:8080 -p 50000:50000 -v /opt/jenkins/:/var/jenkins_home -d --name my-jenkins jenkins/jenkins


# otro:
# sudo docker run -d --name nginx -p 80:80 -v /opt/nginx/:/var/log/nginx nginx
